appointment/urls.py
from django.urls import path
from .views import AppointmentView, AvailabilityView, AppointmentListView, update_event, delete_event

urlpatterns = [
    path("set_appointment/", AppointmentView.as_view(), name="set_appointment"),
    path("appointments/", AppointmentListView.as_view(), name="appointments"),
    path("availability/", AvailabilityView.as_view(), name="availability"),
    path("update_event/", update_event, name="update_event"),
    path("delete_event/<int:pk>/<str:eid>", delete_event, name="delete_event"),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('customauth.urls')),
    path("appointment/", include('appointment.urls')),
]

# Adding static and media urls
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

appointment/models.py
from django.db import models
from service.models import Service
from barber.models import Barber
from user.models import User

class Appointment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_appointments')
    email = models.EmailField(verbose_name='customer email', max_length=254)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name="service_appointments")
    barber = models.ForeignKey(Barber, on_delete=models.CASCADE, related_name="barber_appointments")
    date = models.DateField(auto_now=False, auto_now_add=False)
    time = models.TimeField(auto_now=False, auto_now_add=False)
    status = models.CharField(max_length=150, default="confirmed")
    comments = models.TextField(blank=True, null=True)
    event_id = models.CharField(max_length=250)
    event_url = models.URLField(max_length=500)


    class Meta:
        verbose_name = 'Appointment'
        verbose_name_plural = 'Appointments'

    def __str__(self):
        return self.event_url


payment/models.py
from django.db import models
from appointment.models import Appointment
from user.models import User


class PaymentRecord(models.Model):
    customer_name = models.CharField(max_length=250)
    customer_last_name = models.CharField(max_length=250)
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    payment_method = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'PaymentRecord'
        verbose_name_plural = 'PaymentRecords'

    def __str__(self):
        pass


appointment/forms.py
from django import forms
from .models import Appointment

class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ["email", "service", "barber", "date", "time","comments"]
        exclude = ("user", "status", "event_url", "event_id")
        widgets = {
            "date": forms.DateInput(
                attrs={"type": "date", "class": "form-control", "disabled": True}
            ),
            "time": forms.Select(choices=[], attrs={"disabled": True}),
            "comments": forms.Textarea(attrs={"rows": 5}),
        }

appointment/views.py
import json
import datetime
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, ListView
from utilities.googleCalendar import GoogleCalendar
from utilities.formatTime import get_start_end_time
from .forms import AppointmentForm
from .models import Appointment
from utilities.availability import get_availability
from django.contrib.auth.mixins import LoginRequiredMixin
from .threads import UpdateEventThread, DeleteEventThread


class AppointmentView(LoginRequiredMixin, CreateView):
    login_url = "login"
    template_name = "appointment/set_appointment.html"
    form_class = AppointmentForm

    def form_valid(self, form):
        # Getting form data for create google calendar event
        service = form.cleaned_data["service"]
        barber = form.cleaned_data["barber"]
        date = form.cleaned_data["date"]
        time = form.cleaned_data["time"]
        user = self.request.user
        start_time, end_time = get_start_end_time(date, time)

        # Create google calendar event
        google = GoogleCalendar()

        event = google.create_event(
            f"Appointment for: {service}",
            f"Reserved between {user.first_name} and the barber {barber}",
            f"{start_time}",
            f"{end_time}",
            "America/Chicago",
        )

        # Adding new fields and saving the appointment in the database
        form.instance.user = user
        form.instance.event_url = event["htmlLink"]
        form.instance.event_id = event["id"]
        form.save()

        # Adding a custom event (created) for HTMX 
        response = HttpResponse()
        response["HX-Trigger"] = "created"
        return response


class AvailabilityView(View):
    def post(self, request, *args, **kwargs):
        jsonPost = json.loads(request.body.decode("utf-8"))
        date = jsonPost["date"]
        barber_id = jsonPost["barberId"]
        barber_events = Appointment.objects.filter(
            barber_id=barber_id, date=date
        ).values_list("time")
        available_hours = get_availability(barber_events)
        return JsonResponse({"hours": available_hours, "result": "ok"})


class AppointmentListView(LoginRequiredMixin, ListView):
    login_url = "login"
    model = Appointment
    template_name = "appointment/appointments.html"

    def get_queryset(self):
        queryset = Appointment.objects.filter(user=self.request.user)
        return queryset


def update_event(request):
    if request.method == "POST":
        date = request.POST.get("date")
        str_time = request.POST.get("time") + ":00"
        appointment_id = request.POST.get("appointment-id")
        event_id = request.POST.get("event-id")
        time = datetime.datetime.strptime(str_time, "%H:%M:%S").time()
        time_zone = "America/Chicago"

        if appointment_id and event_id and date and time:
            # Update google calendar event in background
            UpdateEventThread(event_id, date, time, time_zone).start()
            # Update the appointment from database
            appointment = Appointment.objects.get(id=appointment_id)
            appointment.date = date
            appointment.time = time
            appointment.save()
        else:
            print("Some of following was not received: appointment_id | event_id | date | time")
            return HttpResponse("<div class='text-center mt-5'>Something was wrong, check console logs</div>")

    appointments = Appointment.objects.filter(user=request.user)
    context = {"appointment_list": appointments, "status": "deleted"}
    response = render(request,"appointment/list_appointments.html", context)
    return response


def delete_event(request, pk, eid):
    if request.method == "DELETE":
        try:
            # Delete google calendar event in background
            DeleteEventThread(eid).start()
            # Delete the appointment from database
            appointment = Appointment.objects.get(pk=pk)
            appointment.delete()
            user = request.user
            appointment_list = Appointment.objects.filter(user=user)
            context = {"appointment_list": appointment_list}
            response = render(request, "appointment/list_appointments.html", context)
            response["HX-Trigger"] = "deleted"
            return response
        except Exception as e:
            print("Error when trying to retrieve appointment object: " + str(e))
    else:
        return HttpResponse("<div class='text-center mt-5'>Bad Request</div>")

appointment/templates/appointment/appointments.html
{% extends 'customauth/base.html' %}
{% block title %} Appointments {% endblock %}

{% block body %}
<style>
     /* Media queries */
        @media (max-width: 768px) {
            .table-cont>.table{font-size: 0.6em;}
            .table-cont>.table>tbody button{
                font-size: 0.9em !important;
                width: 8em;
                margin-top: 0.5em;
            }
            .table-cont>a{margin-bottom: 5em; font-size: 0.7em;}
            .modal-header>.modal-title{font-size: 1em !important;}
            .modal-body>form>button{font-size: 0.8em;}
            .modal-body>form>div>input{font-size: 0.8em;}
            .modal-body>form>div>select{font-size: 0.8em;}
        }
</style>
{% load static %}
    <div class="container mt-5 mb-5 table-cont">
        <table class="table">
            <thead>
                <tr>
                <th scope="col" class="text-center">Date</th>
                <th scope="col" class="text-center">Time</th>
                <th scope="col" class="text-center">Service</th>
                <th scope="col" class="text-center">Barber</th>
                <th scope="col" class="text-center">Action</th>
                </tr>
            </thead>
            <!-- To show all appointments scheduled by the user -->
            {% include 'appointment/list_appointments.html' %}
        </table>
        <a class="btn btn-secondary" href="{% url 'set_appointment' %}" role="button">Return</a>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="reschedule" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Select a date to check availability</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" id="date-form" 
                hx-post="{% url 'update_event' %}" 
                hx-trigger="submit"
                hx-swap="outerHTML"
                hx-target="#appointment-tbody">                                                                                                                                                                                                                                                                                                                                                                            
                    {% csrf_token %}
                    <div class="mb-5">
                        <input type="date" name="date" class="form-control mb-2" id="newDate">
                        <select name="time" disabled class="select form-select" id="newTime"></select>
                        <input type="text" class="visually-hidden" data-url="{% url 'availability' %}" id="url-availability">
                        <input type="hidden" id="id_appointment" name="appointment-id">
                        <input type="hidden" id="id_event" name="event-id">
                    </div>
                    <button type="submit" class="btn btn-primary" id="btn-submit">Submit</button>
                    <button type="button" class="btn btn-secondary" id="btn-close" data-bs-dismiss="modal">Close</button>
                </form>
            </div>
            </div>
        </div>
    </div>

    <!-- Custom JS script -->
    <script src="{% static 'appointment/js/appointments.js' %}"></script>

    <!-- Sweet alert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        const Toast = Swal.mixin({
            toast: true,
            position: "top",
            showConfirmButton: false,
            timer: 4000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.onmouseenter = Swal.stopTimer;
                toast.onmouseleave = Swal.resumeTimer;
            }
        });

        const showConfirmation = (title) => {
            // Trigger the toast notification
            Toast.fire({
                icon: "success",
                title: title
            });
        }
    </script>
{% endblock %}

appointment/templates/appointment/list_appointments.html
<tbody id="appointment-tbody">
{% for appointment in appointment_list %}
    <tr class="text-center">
        <td>{{appointment.date}}</td>
        <td>{{appointment.time}}</td>
        <td>{{appointment.service}}</td>
        <td>{{appointment.barber}}</td>
        <td>
            <button class="btn btn-danger cancel-btn" type="submit"
            hx-delete="{% url 'delete_event' pk=appointment.id eid=appointment.event_id %}"
            hx-target="#appointment-tbody"
            hx-on:deleted="showConfirmation('Event successfully deleted')"
            hx-swap="outerHTML">
                Cancel
            </button>
            <button type="button" class="btn btn-secondary btn-reschedule" 
                data-bs-toggle="modal" data-bs-target="#reschedule" 
                data-appointmentId={{appointment.id}} 
                data-barberId={{appointment.barber.id}}
                data-eventId={{appointment.event_id}}>
                Reschedule
            </button>
        </td>
    </tr>
{% endfor %}

<!-- To display a sweet alert notification to inform the user -->
{% if status %}
    {% if status == 'deleted' %}
        <script>
            showConfirmation('Event successfully updated')
        </script>
    {% endif %}
{% endif %}

</tbody>    

appointment/templates/appointment/set_appointment.html
{% extends 'customauth/base.html' %}
{% block title %}Appointment Page{% endblock  %}

{% block body %}
{% load crispy_forms_tags %}
{% load static %}
<style>
    .actions-cont>div>p>strong{    
        font-family: "Roboto", sans-serif;
        font-weight: 400;
        font-style: italic;
    }
    .appoint-cont>div>h4{
        font-family: "Roboto", sans-serif;
        font-weight: 400;
        font-style: normal;
    }
    .text-color{color: #607274;}

    /* spinner */
    .loader {
        width: 1.5em;
        height: 1.5em;
        border: 5px solid;
        border-color: #FFFFFF transparent;
        border-radius: 50%;
        display: inline-block;
        box-sizing: border-box;
        animation: rotation 1s linear infinite;
        position: absolute;
        right: 2em;
    }

    @keyframes rotation {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }

    /* Media queries */
        @media (max-width: 768px) {
            .row>div>.appoint-cont{width: 100% !important;}
            .row>div>img{width:60% !important;}
            .row>div{
                display: flex;
                justify-content: center;
                flex-wrap: wrap;
                margin-top: 3em;
            }
            .actions-cont{
                margin-left: 0px !important;
                margin-bottom: 3em;
            }
            .actions-cont>div>a{font-size: 0.7em;}
            .card-body>.text-color{font-size: 0.8em;}
            .card-body>.text-color>div>button{font-size: 1em;}
        }
</style>
{% if 'created' in request.GET %}
    <div class="container d-flex justify-content-center mt-1">
        <div class="alert alert-success alert-dismissible fade show w-50 text-center p-1" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            <p>Appointment created, you should receive an email notification</p>
        </div>
    </div>
{% endif %}
<div class="row g-0 mt-3 mb-5">
    <div class="col-md-4">
        <img src="{% static 'appointment/images/barber-sh.jpg' %}" class="img-fluid rounded-start rounded" alt="business-img">
    </div>
    <div class="col-md-8 p-3 d-flex">
        <div class="card border-light mb-3 w-50 appoint-cont">
            <div class="card-header text-center text-color"><h4>Hi {{request.user.first_name}}! Please fill out the form</h4></div>
            <div class="card-body">
                <form 
                id="appointmentForm"
                method="post" 
                class="text-color" 
                hx-post="{% url 'set_appointment' %}" 
                hx-trigger="submit" 
                hx-indicator=".loader"
                hx-on:created="showConfirmation()" 
                hx-swap="none">
                    {% csrf_token %} {{ form|crispy }}
                    <div class="container">
                        <button type="submit" class="btn btn-primary w-100">
                            Submit
                            <span class="loader htmx-indicator"></span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="text-center ms-5 w-50 actions-cont">
            <div class="mt-4">
                <p><strong class="text-center text-color">
                    Do you have any existing appointments?<br>
                    You can cancel or reschedule any time.
                </strong></p>
                <a class="btn btn-primary mb-3" href="{% url 'appointments' %}" role="button">View Details</a>
            </div>
        </div>
    </div>
</div>
<!-- Store the url to send a POST request in order to get available hours -->
<input class="visually-hidden" type="text" data-url="{% url 'availability' %}" id="url">

<!-- Custom js script -->
<script src="{% static 'appointment/js/set_appointment.js' %}"></script>

<!-- Sweet alert -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    const Toast = Swal.mixin({
        toast: true,
        position: "center",
        showConfirmButton: false,
        timer: 4000,
        timerProgressBar: true,
        didOpen: (toast) => {
            toast.onmouseenter = Swal.stopTimer;
            toast.onmouseleave = Swal.resumeTimer;
        }
    });

    const showConfirmation = () => {
        // Reset the form
        const form = document.getElementById('appointmentForm');
        form.reset(); 

        // Disabling input date and time
        const date = document.getElementById('id_date')
        const time = document.getElementById('id_time')
        time.innerHTML = ''
        time.disabled=true
        date.disabled=true

        // Trigger the toast notification
        Toast.fire({
            icon: "success",
            title: "Event successfully created"
        });
    }
</script>

{% endblock %}
    